#!/usr/bin/env python3
"""Tests for human-readable corpus views generated by incorporate.py."""
import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))
spec = importlib.util.spec_from_file_location("incorporate", SCRIPTS / "incorporate.py")
incorporate = importlib.util.module_from_spec(spec)
spec.loader.exec_module(incorporate)


class IncorporateMarkdownTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.accept = self.root / "accept"
        self.accept.mkdir()
        self.publication_key = "fixture-2020-example"
        self.card = {
            "card_id": f"{self.publication_key}-C0001",
            "category": "prognosis",
            "disease_ancestors": [],
            "diseases": ["AML"],
            "evidence_tier": "multivariable-adjusted",
            "genes": ["GENEA"],
            "interpretation": "GENEA mutation was independently associated with outcome.",
            "locator": "Results, Table 2",
            "secondary_citation": None,
        }
        self.evidence = {
            "card_id": self.card["card_id"],
            "evidence_type": "contiguous_text",
            "fragments": [
                {
                    "fragment_id": "F01",
                    "role": "claim",
                    "quote": "GENEA remained independently associated with outcome.",
                    "locator": "Results, Table 2",
                }
            ],
            "support_map": {"gene": ["F01"], "effect": ["F01"]},
        }
        self.corpus = {
            "publications": [
                {
                    "source": {"input_id": "fixture"},
                    "document": {
                        "publication_key": self.publication_key,
                        "citation": {"display": "Fixture A. Example paper. 2020."},
                        "cards": [self.card],
                    },
                }
            ]
        }
        envelope = {
            "final": {
                "cards": [
                    {
                        key: value
                        for key, value in self.card.items()
                        if key != "disease_ancestors"
                    }
                ],
                "evidence": [self.evidence],
            }
        }
        (self.accept / f"{self.publication_key}.final.json").write_text(
            json.dumps(envelope), encoding="utf-8"
        )

    def tearDown(self):
        self.tmp.cleanup()

    def test_views_separate_cards_from_evidence(self):
        cards, evidence = incorporate.build_markdown_documents(
            self.corpus, self.accept
        )
        cards_text = cards[f"{self.publication_key}.md"]
        evidence_text = evidence[f"{self.publication_key}.md"]

        self.assertIn(self.card["interpretation"], cards_text)
        self.assertIn("**Category:** prognosis", cards_text)
        self.assertNotIn(self.evidence["fragments"][0]["quote"], cards_text)

        self.assertIn(self.card["interpretation"], evidence_text)
        self.assertIn(self.evidence["fragments"][0]["quote"], evidence_text)
        self.assertNotIn("**Category:**", evidence_text)
        self.assertNotIn("**Genes:**", evidence_text)

    def test_replace_deletes_every_existing_markdown_file(self):
        directory = self.root / "cards"
        directory.mkdir()
        (directory / "old-publication.md").write_text("old", encoding="utf-8")
        (directory / "manual-notes.md").write_text("manual", encoding="utf-8")
        (directory / "keep.txt").write_text("keep", encoding="utf-8")

        incorporate.replace_markdown_documents(
            directory, {f"{self.publication_key}.md": "new\n"}
        )

        self.assertEqual(
            sorted(path.name for path in directory.glob("*.md")),
            [f"{self.publication_key}.md"],
        )
        self.assertEqual((directory / "keep.txt").read_text(encoding="utf-8"), "keep")

    def test_replace_with_empty_documents_preserves_existing_files(self):
        directory = self.root / "cards"
        directory.mkdir()
        (directory / "existing.md").write_text("keep me", encoding="utf-8")

        incorporate.replace_markdown_documents(directory, {})

        self.assertTrue((directory / "existing.md").exists())
        self.assertEqual(
            (directory / "existing.md").read_text(encoding="utf-8"), "keep me"
        )

    def test_failed_staging_preserves_existing_markdown_files(self):
        directory = self.root / "cards"
        directory.mkdir()
        existing = directory / "existing.md"
        existing.write_text("keep me", encoding="utf-8")

        with mock.patch.object(
            incorporate, "atomic_text", side_effect=OSError("simulated write failure")
        ):
            with self.assertRaisesRegex(OSError, "simulated write failure"):
                incorporate.replace_markdown_documents(
                    directory, {f"{self.publication_key}.md": "new\n"}
                )

        self.assertEqual(existing.read_text(encoding="utf-8"), "keep me")
        self.assertEqual(
            sorted(path.name for path in directory.glob("*.md")), ["existing.md"]
        )

    def test_zero_card_publication_still_has_one_file_per_publication(self):
        publication_key = "fixture-2020-zero-card"
        corpus = {
            "publications": [
                {
                    "source": {"input_id": "zero"},
                    "document": {
                        "publication_key": publication_key,
                        "citation": {"display": "Fixture B. Zero-card paper. 2020."},
                        "cards": [],
                    },
                }
            ]
        }
        (self.accept / f"{publication_key}.final.json").write_text(
            json.dumps({"final": {"cards": [], "evidence": []}}), encoding="utf-8"
        )

        cards, evidence = incorporate.build_markdown_documents(corpus, self.accept)

        self.assertIn(f"{publication_key}.md", cards)
        self.assertIn(f"{publication_key}.md", evidence)
        self.assertEqual(evidence[f"{publication_key}.md"], "")


if __name__ == "__main__":
    unittest.main()
