#!/usr/bin/env python3
"""Package full legacy or 0.2.2-prototype ngs-report artifacts for debugging."""
from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path

ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)

# Explicit allowlist of artifacts generated by the legacy full ngs-report workflow.
# This avoids accidentally archiving unrelated files from a user-supplied work directory.
RUN_ARTIFACTS = (
    "case.md",
    "case-major-categories.json",
    "case-input.json",
    "diagnostic_evidence.md",
    "diagnostic_evidence.json",
    "adjudication.json",
    "bundle.json",
    "evidence.md",
    "card-tags.json",
    "report-draft.md",
    "report-final.md",
)

PROTOTYPE_RUN_ARTIFACTS = (
    "case.md",
    "case-major-categories.json",
    "case-input.json",
    "diagnostic_evidence.md",
    "diagnostic_evidence.json",
    "reporting-rules-dx.md",
    "report-draft-dx.md",
    "bundle.json",
    "downstream_evidence.md",
    "reporting-rules-remainder.md",
    "evidence.md",
    "card-tags.json",
    "report-draft-remainder.md",
    "report-draft.md",
    "report-final.md",
)


def _write_file(zf: zipfile.ZipFile, path: Path, arcname: str) -> None:
    info = zipfile.ZipInfo(arcname, ZIP_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    zf.writestr(info, path.read_bytes())


def _artifact_allowlist(work_dir: Path):
    """Select the debug bundle profile without changing legacy CLI behaviour."""
    diagnostic_json = work_dir / "diagnostic_evidence.json"
    if diagnostic_json.is_file():
        try:
            payload = json.loads(diagnostic_json.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            # Preserve the historical package_run contract for legacy work
            # directories/tests that only require this filename to exist. If
            # prototype-only artefacts are present, however, malformed profile
            # JSON is a real routing error and must fail closed.
            if (work_dir / "report-draft-dx.md").is_file() or (
                work_dir / "reporting-rules-dx.md"
            ).is_file():
                raise ValueError(
                    f"cannot identify prototype workflow profile because {diagnostic_json} "
                    f"is invalid JSON: {exc}"
                ) from exc
            return RUN_ARTIFACTS
        if payload.get("workflow_profile") == "0.2.2_prototype":
            return PROTOTYPE_RUN_ARTIFACTS
    return RUN_ARTIFACTS


def package_run_bundle(work_dir: Path, output_path: Path) -> Path:
    work_dir = work_dir.resolve()
    if not work_dir.is_dir():
        raise FileNotFoundError(f"work directory not found: {work_dir}")

    artifacts = _artifact_allowlist(work_dir)
    missing = [name for name in artifacts if not (work_dir / name).is_file()]
    if missing:
        raise FileNotFoundError(
            "cannot package the debug ZIP because these required workflow artifacts are missing: "
            + ", ".join(missing)
            + ". Do not fabricate or hand-edit missing deterministic artifacts. Resume/rerun the "
              "workflow step that produces each missing file, then rerun Step 7A packaging."
        )

    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w") as zf:
        for name in artifacts:
            _write_file(zf, work_dir / name, name)

    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Package all artifacts generated by a full ngs-report workflow."
    )
    parser.add_argument("--work-dir", type=Path, required=True, help="NGS report working directory")
    parser.add_argument("--output", type=Path, required=True, help="Output debug ZIP path")
    args = parser.parse_args()

    try:
        path = package_run_bundle(args.work_dir, args.output)
    except (OSError, ValueError) as exc:
        parser.exit(1, f"Error: {exc}\n")

    print(path)


if __name__ == "__main__":
    main()
