#!/usr/bin/env python3
"""Package the debug artifacts declared by the workflow bound to a work directory."""
from __future__ import annotations

import argparse
import zipfile
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
from scripts.workflow_registry import workflow_for_work_dir

ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)


def _write_file(zf: zipfile.ZipFile, path: Path, arcname: str) -> None:
    info = zipfile.ZipInfo(arcname, ZIP_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    zf.writestr(info, path.read_bytes())


def artifact_allowlist(work_dir: Path) -> tuple[str, ...]:
    _workflow_id, metadata = workflow_for_work_dir(work_dir)
    artifacts = metadata.get("artifacts")
    if not isinstance(artifacts, list) or not artifacts or any(
        not isinstance(name, str) or not name for name in artifacts
    ):
        raise ValueError("workflow metadata has no valid artifact allowlist")
    return tuple(artifacts)


def package_run_bundle(work_dir: Path, output_path: Path) -> Path:
    work_dir = work_dir.resolve()
    if not work_dir.is_dir():
        raise FileNotFoundError(f"work directory not found: {work_dir}")

    artifacts = artifact_allowlist(work_dir)
    missing = [name for name in artifacts if not (work_dir / name).is_file()]
    if missing:
        raise FileNotFoundError(
            "cannot package the debug ZIP because these required workflow artifacts are missing: "
            + ", ".join(missing)
            + ". Do not fabricate or hand-edit missing deterministic artifacts. Resume/rerun the "
              "workflow step that produces each missing file, then rerun Step 7 packaging."
        )

    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w") as zf:
        for name in artifacts:
            _write_file(zf, work_dir / name, name)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Package all artifacts generated by a full ngs-report workflow."
    )
    parser.add_argument("--work-dir", type=Path, required=True, help="NGS report working directory")
    parser.add_argument("--output", type=Path, required=True, help="Output debug ZIP path")
    args = parser.parse_args()
    try:
        path = package_run_bundle(args.work_dir, args.output)
    except (OSError, ValueError) as exc:
        parser.exit(1, f"Error: {exc}\n")
    print(path)


if __name__ == "__main__":
    main()
