#!/usr/bin/env python3
"""Package the files generated by a full ngs-report workflow for debugging."""
from __future__ import annotations

import argparse
import zipfile
from pathlib import Path

ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)

# Explicit allowlist of artifacts generated by the full ngs-report workflow.
# This avoids accidentally archiving unrelated files from a user-supplied work directory.
RUN_ARTIFACTS = (
    "case.md",
    "case-major-categories.json",
    "case-input.json",
    "diagnostic_evidence.md",
    "adjudication.json",
    "bundle.json",
    "evidence.md",
    "card-tags.json",
    "report-draft.md",
    "report-final.md",
)


def _write_file(zf: zipfile.ZipFile, path: Path, arcname: str) -> None:
    info = zipfile.ZipInfo(arcname, ZIP_TIMESTAMP)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    zf.writestr(info, path.read_bytes())


def package_run_bundle(work_dir: Path, output_path: Path) -> Path:
    work_dir = work_dir.resolve()
    if not work_dir.is_dir():
        raise FileNotFoundError(f"work directory not found: {work_dir}")

    missing = [name for name in RUN_ARTIFACTS if not (work_dir / name).is_file()]
    if missing:
        raise FileNotFoundError(
            "full ngs-report artifacts missing from work directory: " + ", ".join(missing)
        )

    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w") as zf:
        for name in RUN_ARTIFACTS:
            _write_file(zf, work_dir / name, name)

    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Package all artifacts generated by a full ngs-report workflow."
    )
    parser.add_argument("--work-dir", type=Path, required=True, help="NGS report working directory")
    parser.add_argument("--output", type=Path, required=True, help="Output debug ZIP path")
    args = parser.parse_args()

    try:
        path = package_run_bundle(args.work_dir, args.output)
    except OSError as exc:
        parser.exit(1, f"Error: {exc}\n")

    print(path)


if __name__ == "__main__":
    main()
